export const SCENTS = [
  "Unscented",
  "Jasmine",
  "Vanilla",
  "Rain Water",
  "Fresh Linen",
  "Star Gazer Lily",
  "Cherry Blossom",
  "Honeysuckle",
  "Zippity Do Dah",
];

export const COLORS = [
  "White",
  "Yellow",
  "Blue",
  "Red",
  "Purple",
  "Orange",
  "Pink",
  "Aquamarine",
  "Bright Green",
];

export type Product = {
  id: number;
  name: string;
  price: number;
  category: "logo" | "handbag" | "fashion" | "decorative";
  image: string;
  dimensions: string;
  weight: string;
  scents: string[];
  colors: string[];
};

export const products: Product[] = [
  {
    id: 1,
    name: "CC Letters",
    price: 30,
    category: "logo",
    image: "/images/01.png",
    dimensions: "12.3 x 16 cm (4.84 x 6.30 in)",
    weight: "290g (10.23oz)",
    scents: SCENTS,
    colors: COLORS,
  },
  {
    id: 2,
    name: "LV Letters",
    price: 30,
    category: "logo",
    image: "/images/02.png",
    dimensions: "14.5 x 14.5 cm (5.71 x 5.71 in)",
    weight: "307g (10.83oz)",
    scents: SCENTS,
    colors: COLORS,
  },
  {
    id: 3,
    name: "GG Letters",
    price: 30,
    category: "logo",
    image: "/images/03.png",
    dimensions: "16 x 12.5 cm (6.30 x 4.92 in)",
    weight: "300g (10.58oz)",
    scents: SCENTS,
    colors: COLORS,
  },
  {
    id: 4,
    name: "CC Bag",
    price: 30,
    category: "handbag",
    image: "/images/04.png",
    dimensions: "10.4 x 7.6 cm (4.09 x 2.99 in)",
    weight: "280g (9.88oz)",
    scents: SCENTS,
    colors: COLORS,
  },
  {
    id: 5,
    name: "YSL Flap",
    price: 35,
    category: "handbag",
    image: "/images/05.png",
    dimensions: "14.4 x 8.2 cm (5.67 x 3.23 in)",
    weight: "365g (12.87oz)",
    scents: SCENTS,
    colors: COLORS,
  },
  {
    id: 6,
    name: "Dionysus",
    price: 35,
    category: "handbag",
    image: "/images/06.png",
    dimensions: "16.2 x 10.5 cm (5.83 x 3.74 in)",
    weight: "385g (13.58oz)",
    scents: SCENTS,
    colors: COLORS,
  },
  {
    id: 7,
    name: "Marmont",
    price: 40,
    category: "handbag",
    image: "/images/07.png",
    dimensions: "14.5 x 10 cm (5.71 x 3.94 in)",
    weight: "550g (19.40oz)",
    scents: SCENTS,
    colors: COLORS,
  },
  {
    id: 8,
    name: "CC Clutch",
    price: 40,
    category: "handbag",
    image: "/images/08.png",
    dimensions: "14.3 x 9 cm (5.63 x 3.54 in)",
    weight: "420g (14.82oz)",
    scents: SCENTS,
    colors: COLORS,
  },
  {
    id: 9,
    name: "Dauphine",
    price: 40,
    category: "handbag",
    image: "/images/09.png",
    dimensions: "13.1 x 5.7 cm (5.16 x 2.24 in)",
    weight: "461g (16.26oz)",
    scents: SCENTS,
    colors: COLORS,
  },
  {
    id: 10,
    name: "YSL Envelope",
    price: 40,
    category: "handbag",
    image: "/images/10.png",
    dimensions: '14.8 x 10.5 x 6 cm (5.83 x 4.13 x 2.36 in)',
    weight: "586g (20.66oz)",
    scents: SCENTS,
    colors: COLORS,
  },
  {
    id: 11,
    name: "LV Pillar",
    price: 40,
    category: "handbag",
    image: "/images/11.jpg",
    dimensions: "12 x 9.5 cm (4.72 x 3.74 in)",
    weight: "600g (21.16oz)",
    scents: SCENTS,
    colors: COLORS,
  },
  {
    id: 12,
    name: "LV Bucket",
    price: 45,
    category: "handbag",
    image: "/images/12.png",
    dimensions: '10.8 x 8.3 x 10.5 cm (4.25 x 3.27 x 4.13 in)',
    weight: "600g (21.16oz)",
    scents: SCENTS,
    colors: COLORS,
  },
  {
    id: 13,
    name: "Trunk",
    price: 50,
    category: "handbag",
    image: "/images/13.png",
    dimensions: '13.5 x 8.5 x 7.5 cm (5.31 x 3.35 x 2.95 in)',
    weight: "825g (29.10oz)",
    scents: SCENTS,
    colors: COLORS,
  },
  {
    id: 14,
    name: "Chapeau",
    price: 50,
    category: "fashion",
    image: "/images/14.jpg",
    dimensions: '12.9 x 6.5 x 11.6 cm (5.08 x 2.56 x 4.57 in)',
    weight: "560g (19.76oz)",
    scents: SCENTS,
    colors: COLORS,
  },
  {
    id: 15,
    name: "Hermes",
    price: 55,
    category: "handbag",
    image: "/images/15.png",
    dimensions: "17 x 11.8 cm (6.06 x 4.65 in)",
    weight: "710g (25.04oz)",
    scents: SCENTS,
    colors: COLORS,
  },
  {
    id: 16,
    name: "Speedy",
    price: 55,
    category: "handbag",
    image: "/images/16.png",
    dimensions: '16 x 13.4 x 11.3 cm (6.30 x 5.28 x 4.45 in)',
    weight: "890g (31.39oz)",
    scents: SCENTS,
    colors: COLORS,
  },
  {
    id: 17,
    name: "LV Duffel",
    price: 55,
    category: "handbag",
    image: "/images/17.png",
    dimensions: "17.5 x 8.7 cm (5.63 x 3.54 in)",
    weight: "790g (27.86oz)",
    scents: SCENTS,
    colors: COLORS,
  },
  {
    id: 18,
    name: "XL Flap",
    price: 55,
    category: "handbag",
    image: "/images/18.png",
    dimensions: "17.5 x 9 cm (6.89 x 3.54 in)",
    weight: "745g (26.28oz)",
    scents: SCENTS,
    colors: COLORS,
  },
];
