name = "candles-by-tj"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "candles-by-tj"
database_id = "f9002a71-2659-41c7-a82a-9b482101a9db"

[vars]
ENVIRONMENT = "production"
